utf8.h
=> Fix pointer comparison in utf8str

utf8.h
I tried to replace int with long in utf8chr. I had no problem with the tests on travis.
So this commit should pass the tests.
This pull request is based on #11
=> Replaced int with long in utf8chr. Based on #11

README.md, test/main.c, test/utest.h, utf8.h
Pulled in the fix from @chloridite, fixed it up for Windows, and also ported the testing over to utest.h too (fixes #17).
=> Add casestr

README.md
As a starting point, as mentioned in #6. 
More nuance and detail can be added with less effort then.
=> Add function docs (from header => readme)

utf8.h
Partially fixes #14. Added restrict where appropriate for the functions (useful hint to the optimizer).
=> Add restrict where appropriate.

README.md, test/main.c, utf8.h
Let me know if this looks okay. I haven't done huge testing on this yet, but the quick tests seem to go fine.
Talking about tests, I'm also not sure how to add unit tests to this pull request. Any tips?
=> Added utf8codepointsize and utf8addcodepoint

utf8.h
=> Fix unsafe code in utf8str

test/main.c, utf8.h
By introducing a unique utf8_int32_t typedef.
=> fix the int32_t alias problem

test/main.c, utf8.h
=> Fix the overflow in utf8ncpy.

test/main.c, utf8.h
Pull in https://github.com/sheredom/utf8.h/pull/55 and try to get it building on old MSVC.
=> Roxas232 utf8str infinite loop

test/main.c, test/utest.h, utf8.h
=> Fix the utf8casecmp bug with ascii.

utf8.h
=> Fix utf8size being declared.

.github/workflows/cmake.yml, README.md, test/main.c, test/utest.h, utf8.h
=> Fix the greek capital theta bug.

README.md, test/main.c, utf8.h
=> Add a utf8makevalid.

.clang-format, utf8.h
I used the default style, but you can try more here https://zed0.co.uk/clang-format-configurator/
=> Add clang format

test/main.c, utf8.h
=> Fix the utf8ncat bug a user found.

.github/workflows/cmake.yml, test/CMakeLists.txt, test/main.c, test/no_malloc.c, utf8.h
=> Add support for having no malloc function.

utf8.h
https://github.com/sheredom/utf8.h/issues/109
=> fix for issue 109

test/main.c, utf8.h
=> Fix another rchr bug.

.github/workflows/cmake.yml, test/CMakeLists.txt
This is a follow-up to #127 to add testing.
=> Add tests when char_t is disabled on C++20.
