utf8.h
If the `src` argument to `utf8cpy` is `""`, the empty string, `'\0'` is assigned twice to `dst`, once in the loop and the second time after it.
I believe this is not the intended behavior of this function.
=> Two NULs copied to dst when copying "" using utf8cpy

utf8.h
When src argument to utf8cat is an empty string, memory is accessed
outside of its bounds.
Similar bug as the previous.
=> Fix undefined behavior on empty string in utf8cat

utf8.h
Clang was optimizing these out of existence.
=> Fix non-pure functions incorrectly marked as pure.

README.md, test/main.c, utf8.h
- *utf8ncasecmp* only ignores cases of ASCII values.
- I also added new test cases in *test/main.c*.
- Tested with GCC 4.6.3 and clang 3.4. Not tested with MSVC.
=> First version of utf8ncasecmp

README.md, test/main.c, utf8.h
utf8codepoint allows user to much more easily iterate through a utf8 string.
For example:
```
void *data = ...; // some utf8 string
long codepoint;
unsigned expected_length = utf8len(data) - 1;
for (void *v = utf8codepoint(data, &codepoint); '\0' != codepoint;
v = utf8codepoint(v, &codepoint)) {
// use codepoint as your utf8 codepoint!
// expected_length is equal to utf8len(v);
expected_length -= 1;
}
```
=> Add utf8codepoint

README.md
It said `utf8addcodepoint` while we renamed it :)
=> Fix function name in readme

README.md, test/main.c, utf8.h
As discussed earlier in #25, I didn't mark these as "complete" in the readme because they really only cover the `A-Za-z` range. `utf8islower` is dumb and only returns `0` for every codepoint in the `A-Z` range.
The upside is that we can use these functions on any utf-8 string or codepoint and they will include any ascii characters.
Thoughts?
=> Added utf8islower, utf8isupper, utf8lwr, utf8upr

test/main.c
on 64bit codepoint overflew to 4294967296
=> fix 64bit Debug test utf8codepoint.data

utf8.h
The utf8casestr function had a bug that prevented needle from being found in haystack when the needle existed at the end of haystack. This commit fixes that.
For example, the string "Hi\0" (null-terminator for emphasis) as the haystack and "HI\0" as the needle where the needle is stored in dynamic memory and haystack may or may not be. utf8casestr will continue going as long as they are both equal, even if they continue being equal past their actual lengths. However, once needle is not equivalent to '\0' after the end of the string, it determines that the needle did not exist in the haystack.
=> Bug preventing needle from being found.

.clang-format, README.md, test/main.c, utf8.h
=> Add support for latin case compares.

test/main.c, utf8.h
=> Fix the utf8ncpy overrun problem by making the function less awful C.

test/main.c, utf8.h
Without this fix, utf8str( "foobar", "oba" ) returned NULL.
=> Fix for utf8str when the needle partially matches (foobar, oba)

test/main.c, utf8.h
This example shows why the previous test values were off by one:
```
#include <iostream>
#include <string.h>
using namespace std;
int main()
{
auto len = strspn("abcdefg", "abc");
cout<< len << endl; // 3
len = strspn("abcdefg", "abcdefg");
cout<< len; // 7
return 0;
}
```
=> Fix for utf8spn not matching ASCII characters

README.md, utf8.h
There is a small typo in README.md, utf8.h.
Should read `occurrence` rather than `occurence`.
=> docs: fix simple typo, occurence -> occurrence

README.md, test/main.c, utf8.h
Prevent utf8ncpy producing an invalid utf8 string if destination buffer size cut short a codepoint or didn't leave room for a null terminator
=> utf8ncpy fix

README.md, test/main.c, utf8.h
=> Add a function to get the previous codepoint.

test/main.c, utf8.h
=> Add utf8dup_ex and utf8ndup_ex to allow users to never use malloc.

utf8.h
I fixed an issue that `utf8ncpy` referred `dst` even if `n` is zero.
valgrind said:
```
==550== Conditional jump or move depends on uninitialised value(s)
==550==    at 0x10C2BB: utf8ncpy (utf8.h:644)
```
=> Fix utf8ncpy not to refer uninitialized value.

README.md, test/CMakeLists.txt, test/main.c, test/test.cpp, utf8.h
This feature required more changes than expected. I will understand if you prefer not to merge it
See the commit history for details, and please ask me anything if you need to
=> Add constexpr to most functions (use char8_t for C++20)

test/main.c, utf8.h
Hi @sheredom ,
`utf8ncasecmp("Camón Romasan", "camu", 4)` returns 0, which I believe is incorrect.
The proposed patch fixes this. I also added a test case for it.
=> Fix utf8ncasecmp bug, not allowing for negative return. Add test case.

utf8.h
Spotted by Coverity Scan on the copy of utf8.h integrated into GDAL
=> Remove dead cases in utf8lwrcodepoint() and utf8uprcodepoint()

test/test.cpp, utf8.h
This commit removes the need to include `/Zc:__cplusplus` in Visual Studio projects, by replacing `__cplusplus` macro with `utf8_cplusplus`, which uses `_MSVC_LANG` to get the current C++ version. On other compilers `utf8_cplusplus` is defined as `__cplusplus`.
=> Better compatibility with MSVC compiler

utf8.h
This PR adds support for compilation in C++20 without having `char8_t` enabled.
`char8_t` can be manually disabled on MSVC using `/Zc:char8_t-` and on GCC/clang with `-fno-char8_t`
=> Add support for C++20 without char8_t

utf8.h
This PR adds support for the IAR compiler.
=> Add IAR compiler attribute definitions
